<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kbot">

  <xacro:include filename="$(find mybot_description)/urdf/properties.xacro" />
  <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find mybot_description)/urdf/kbot_macros.xacro" />
  <xacro:if value="${gazebo == 'true'}">
    <xacro:include filename="$(find mybot_description)/urdf/kbot.gazebo" />
  </xacro:if>

  <!-- The physic engine does not accept a base_link with inertia. It is then useful to
       add a simple link without inertia and make a joint between it and the chassis
    -->
  <link name="base_footprint">
    <!--
        <xacro:box_inertia m="20" w="0.001" h="0.001" d="0.001" />
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
      -->
  </link>

  <link name="base_link">
    <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}" />
      </geometry>
      <material name="gold" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}" />
      </geometry>
    </collision>
  </link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 ${base_radius}" rpy="0 0 0" />
    -->
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>

  <link name="caster_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${caster_wheel_radius}" />
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${caster_wheel_radius}" />
      </geometry>
    </collision>
    <xacro:sphere_inertia m="${caster_wheel_mass}" r="${caster_wheel_radius}" />
  </link>

  <joint name="caster_wheel_joint" type="fixed">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="caster_wheel" />
    <origin xyz="${caster_wheel_joint_offset} 0 -${caster_wheel_radius}" rpy="0 0 0" />
  </joint>

  <xacro:wheel prefix="left" reflect="1" />
  <xacro:wheel prefix="right" reflect="-1" />

  <link name="laser_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${hokuyo_size}" length="0.04" />        
      </geometry>
      <material name="blue" />
    </visual>
  </link>
  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="0 0 ${base_height+hokuyo_size/4}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="laser_link" />
  </joint>
  <!-- 
    <link name="camera">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
        </geometry>
      </collision>
    
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
        </geometry>
        <material name="blue"/>
      </visual>    

      <xacro:box_inertia m="${cameraMass}" w="${cameraSize}" h="${cameraSize}" d="${cameraSize}" />
      
    </link>
  -->
</robot>