<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="roachbot">
  <!-- 
  These properties must be observed by any machine
  that wants to be defined as a turtlebot. Refer
  to the REP for more details.    
  http://www.ros.org/reps/rep-0119.html     
  
 ======================================================================
  REP 119 : Rgb camera link relative to the Base link 
 ====================================================================== 
   Base link is currently defined as the rotational centre on the bottom
   of the base mould. For both create and kobuki this is actually exactly
   the same 3d world point. 
   
   This may cause an issue with a base with much different floor clearance.
   Should we be using base_footprint for this specification instead?
   Note: REP needs to be updated with the information below 
   (currently in development and awaiting feedback)
-->
  
  <xacro:property name="gazebo" value="true" />

  <xacro:property name="hokuyo_size" value="0.03" /> 

  <xacro:property name="cam_px" value="-0.087" />
  <xacro:property name="cam_py" value="-0.0125" />
  <xacro:property name="cam_pz" value="0.2870" />
  <xacro:property name="cam_or" value="0" />
  <xacro:property name="cam_op" value="0" />
  <xacro:property name="cam_oy" value="0" />
  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI_2" value="${pi/2}" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />
  <!-- Main body radius and height -->
  <!-- Main Body Cylinder base   -->
  <xacro:property name="base_width" value="0.16" />
  <xacro:property name="base_len" value="0.16" />

  <xacro:property name="base_height" value="0.01" />
  <xacro:property name="base_radius" value="0.07" />
  <xacro:property name="base_mass" value="4.0" /> <!-- in kg-->
  <xacro:property name="wheel_separation" value="${2*(wheel_radius+0.5*wheel_thick)" />
  <xacro:property name="wheel_thick" value="0.01" />
  <xacro:property name="base_wheel_gap" value="${base_radius*0.15}" />

  <!-- Wheels -->
  <xacro:property name="wheel_radius" value="0.035" />
  <xacro:property name="wheel_mass" value="0.5" /> <!-- in kg-->

  <xacro:property name="wheel_joint_offset" value="0.02" />
  <xacro:property name="base_x_origin_to_wheel_origin" value="0.25" />
  <xacro:property name="base_y_origin_to_wheel_origin" value="0.3" />
  <xacro:property name="base_z_origin_to_wheel_origin" value="0.0" />

  <xacro:property name="caster_wheel_radius" value="${wheel_radius*0.5}" />
  <xacro:property name="caster_wheel_mass" value="0.1" />
  <xacro:property name="caster_wheel_joint_offset" value="0.052" />

  <xacro:property name="cameraSize" value="0.05" />
  <xacro:property name="cameraMass" value="0.1" />

</robot>